// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SvoyaIgra.DbMigrations.DbContexts;

#nullable disable

namespace SvoyaIgra.DbMigrations.Migrations.SvoyaIgra
{
    [DbContext(typeof(SvoyaIgraDbMigrationContext))]
    partial class SvoyaIgraDbMigrationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SvoyaIgra.Dal.Bo.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("MultimediaId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nchar(36)")
                        .IsFixedLength();

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Question", "SvoyaIgra");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Answer!",
                            Difficulty = 1,
                            MultimediaId = "00000000-0000-0000-0000-000000000000",
                            Text = "Question?",
                            TopicId = 1,
                            Type = 1
                        });
                });

            modelBuilder.Entity("SvoyaIgra.Dal.Bo.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Topic", "SvoyaIgra");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Difficulty = 1,
                            Name = "Tema1"
                        },
                        new
                        {
                            Id = 2,
                            Difficulty = 2,
                            Name = "Tema2"
                        });
                });

            modelBuilder.Entity("SvoyaIgra.Dal.Bo.Question", b =>
                {
                    b.HasOne("SvoyaIgra.Dal.Bo.Topic", "Topic")
                        .WithMany("Questions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SvoyaIgra.Dal.Bo.Topic", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
